Fou_Eng = float(82.4)
Gen_Bus = float(75.3)
Int_Com = float(90.2)
Com_Pro = float(85.9)
print("---Your Score---")
print("Foundation English               : ",Fou_Eng)
print("General Business                 : ",Gen_Bus)
print("Introduction to Computer Systems : ",Int_Com)
print("Computer Programming             : ",Com_Pro)